language: csharp
solution: csharp-csv-reader.sln
install:
  - nuget restore csharp-csv-reader.sln
  - nuget install NUnit -Version 3.6.0 -OutputDirectory nunit
  - nuget install NUnit.Console -Version 3.6.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Debug csharp-csv-reader.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.6.0/tools/nunit3-console.exe ./tests/bin/Debug/CSVTestSuite.net20.dll
  - mono ./testrunner/NUnit.ConsoleRunner.3.6.0/tools/nunit3-console.exe ./tests/bin/Debug/CSVTestSuite.net35.dll
  - mono ./testrunner/NUnit.ConsoleRunner.3.6.0/tools/nunit3-console.exe ./tests/bin/Debug/CSVTestSuite.net40.dll
after_success:
  - echo "Branch is $TRAVIS_BRANCH"
  - echo "Pull Request is $TRAVIS_PULL_REQUEST_BRANCH"
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST_BRANCH" == "" ]; then echo "I would publish to nuget here"; fi